version: '3.9'
services:

  wordpress:
    # default port 9000 (FastCGI)
    image: wordpress:6.4.1-fpm
    container_name: anbernic-wp-fpm
    env_file:
      - .anbernic.deals.env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - database
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

      - WORDPRESS_AUTH_KEY=${WORDPRESS_AUTH_KEY}
      - WORDPRESS_SECURE_AUTH_KEY=${WORDPRESS_SECURE_AUTH_KEY}
      - WORDPRESS_LOGGED_IN_KEY=${WORDPRESS_LOGGED_IN_KEY}
      - WORDPRESS_NONCE_KEY=${WORDPRESS_NONCE_KEY}
      - WORDPRESS_AUTH_SALT=${WORDPRESS_AUTH_SALT}
      - WORDPRESS_SECURE_AUTH_SALT=${WORDPRESS_SECURE_AUTH_SALT}
      - WORDPRESS_LOGGED_IN_SALT=${WORDPRESS_LOGGED_IN_SALT}
      - WORDPRESS_NONCE_SALT=${WORDPRESS_NONCE_SALT}

  database:
    # default port 3306
    image: mariadb
    container_name: anbernic-wp-db
    env_file:
      - .anbernic.deals.env
    restart: unless-stopped
    networks:
      - wordpress
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME}:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx
    container_name: anbernic-wp-ngx
    env_file:
      - .anbernic.deals.env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - "45.76.172.81:80:80" # http
      - "45.76.172.81:443:443" # https
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx
  # adminer - bring up only as needed - bypasses nginx
  #  adminer:
  #    # default port 8080
  #    image: adminer:4
  #    container_name: wp-adminer
  #    restart: unless-stopped
  #    networks:
  #      - wordpress
  #    depends_on:
  #      - database
  #    ports:
  #      - "9000:8080"

networks:
  wordpress:
    name: wp-ngx-anbernic
    driver: bridge
